/**
 * Maps each breed ID to its Dog CEO API path.
 * Format: "breed" or "breed/subbreed"
 * null = not available in Dog CEO API → falls back to place.dog
 *
 * Conservative: when uncertain about a slug, use null.
 * place.dog shows a real dog photo and is preferable to a 404.
 */
export const DOG_CEO_SLUGS: Record<string, string | null> = {
  // ── Popular Purebreds ──────────────────────────────────────────
  "labrador-retriever":          "labrador",
  "golden-retriever":            "retriever/golden",
  "german-shepherd":             "germanshepherd",
  "french-bulldog":              "bulldog/french",
  "bulldog":                     "bulldog/english",
  "poodle":                      "poodle/standard",
  "beagle":                      "beagle",
  "rottweiler":                  "rottweiler",
  "yorkshire-terrier":           "terrier/yorkshire",
  "boxer":                       "boxer",
  "dachshund":                   "dachshund",
  "siberian-husky":              "husky",
  "great-dane":                  "dane/great",
  "doberman-pinscher":           "doberman",
  "shih-tzu":                    "shihtzu",
  "border-collie":               "collie/border",
  "chihuahua":                   "chihuahua",
  "pomeranian":                  "pomeranian",
  "maltese":                     "maltese",
  "cocker-spaniel":              "spaniel/cocker",
  "dalmatian":                   "dalmatian",
  "pug":                         "pug",
  "akita":                       "akita",
  "samoyed":                     "samoyed",
  "chow-chow":                   "chow",
  "australian-shepherd":         "australian/shepherd",
  "pembroke-welsh-corgi":        "pembroke",
  "bernese-mountain-dog":        "mountain/bernese",
  "saint-bernard":               "stbernard",
  "greyhound":                   "greyhound",
  "shiba-inu":                   "shiba",
  "alaskan-malamute":            "malamute",
  "shar-pei":                    "sharpei",
  "afghan-hound":                "hound/afghan",
  "bloodhound":                  "hound/blood",
  "irish-setter":                "setter/irish",
  "bichon-frise":                "frise/bichon",
  "miniature-schnauzer":         "schnauzer/miniature",
  "portuguese-water-dog":        null,
  "newfoundland":                "newfoundland",
  "leonberger":                  "leonberg",
  "belgian-malinois":            "malinois",
  "cavalier-king-charles":       null,
  "boston-terrier":              "bulldog/boston",
  "rhodesian-ridgeback":         "ridgeback/rhodesian",
  "old-english-sheepdog":        "sheepdog/english",
  "west-highland-white-terrier": "terrier/westhighland",
  "scottish-terrier":            "terrier/scottish",
  "italian-greyhound":           "greyhound/italian",
  "irish-wolfhound":             "wolfhound/irish",
  "tibetan-mastiff":             null,
  "english-springer-spaniel":    "springer/english",
  "miniature-pinscher":          "pinscher/miniature",
  "vizsla":                      "vizsla",
  "weimaraner":                  "weimaraner",
  "bull-terrier":                "terrier/bull",
  "basenji":                     "basenji",
  "whippet":                     "whippet",
  "english-setter":              "setter/english",
  "gordon-setter":               "setter/gordon",
  "keeshond":                    "keeshond",
  "norwegian-elkhound":          "elkhound/norwegian",
  "finnish-spitz":               "finnish/spitz",
  "soft-coated-wheaten-terrier": "terrier/wheaten",
  "airedale-terrier":            "airedale",
  "australian-cattle-dog":       "cattledog/australian",
  "cardigan-welsh-corgi":        "corgi/cardigan",
  "black-russian-terrier":       null,
  "bouvier-des-flandres":        null,
  "giant-schnauzer":             "schnauzer/giant",
  "flat-coated-retriever":       "retriever/flatcoated",
  "irish-water-spaniel":         "spaniel/irish",
  "welsh-springer-spaniel":      "spaniel/welsh",

  // ── Designer / Mixed Breeds ───────────────────────────────────
  "goldendoodle":                null,
  "labradoodle":                 null,
  "cockapoo":                    null,
  "cavapoo":                     null,
  "bernedoodle":                 null,
  "aussiedoodle":                null,
  "pomsky":                      null,
  "morkie":                      null,
  "maltipoo":                    null,
  "sheepadoodle":                null,
  "schnoodle":                   null,
  "yorkipoo":                    null,
  "puggle":                      null,
  "shorkie":                     null,
  "cavachon":                    null,

  // ── Protection / Guard Breeds ─────────────────────────────────
  "american-pit-bull-terrier":   "pitbull",
  "american-staffordshire-terrier": "bullterrier/staffordshire",
  "dogo-argentino":              null,
  "presa-canario":               null,
  "boerboel":                    null,
  "caucasian-shepherd":          null,
  "central-asian-shepherd":      null,
  "fila-brasileiro":             null,
  "american-bulldog":            null,
  "czechoslovakian-wolfdog":     null,
  "cane-corso":                  null,
  "tosa-inu":                    null,

  // ── Herding / Pastoral ────────────────────────────────────────
  "havanese":                    "havanese",
  "papillon":                    "papillon",
  "belgian-tervuren":            "tervuren",
  "belgian-sheepdog":            "groenendael",
  "dutch-shepherd":              null,
  "anatolian-shepherd":          null,
  "kangal":                      null,

  // ── Mastiffs ──────────────────────────────────────────────────
  "english-mastiff":             "mastiff/english",
  "neapolitan-mastiff":          null,
  "bullmastiff":                 "mastiff/bull",

  // ── Rare / Unique ─────────────────────────────────────────────
  "american-eskimo-dog":         "eskimo",
  "spinone-italiano":            null,
  "lagotto-romagnolo":           null,
  "xoloitzcuintli":              "mexicanhairless",
  "komondor":                    "komondor",
  "kuvasz":                      "kuvasz",
  "peruvian-inca-orchid":        null,
};

export function getDogCeoApiUrl(breedId: string): string | null {
  const slug = DOG_CEO_SLUGS[breedId];
  if (slug == null) return null;
  return `https://dog.ceo/api/breed/${slug}/images/random`;
}
